[alembic]
# Localização da pasta de migrações
script_location = alembic

# A URL de conexão com caminho absoluto para evitar erros no Windows
sqlalchemy.url = sqlite:///C:\Users\rafae\Documents\Code\Cinema\backend\kinoplex.db

# --- CONFIGURAÇÕES DE LOGGING ---
# Essenciais para você ver o que o Alembic está fazendo no terminal
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
