"""Alterando status e tipo de assento para Enum

Revision ID: 2aa77c9f83cc
Revises: c60308a9ab1a
Create Date: 2026-04-03 00:53:14.651238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aa77c9f83cc'
down_revision: Union[str, Sequence[str], None] = 'c60308a9ab1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
